### ISSUE TITLE
PgSQL problem: Peer authentication failed for user "alaveteli"

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/alaveteli#4]
Cron <root@imamopravoznati> /var/www/imamopravoznati/alaveteli/commonlib/bin/run-with-lockfile.sh -n /var/www/imamopravoznati/load-mail-server-logs.lock /var/www/imamopravoznati/alaveteli/script/load-mail-server-logs || echo "stalled?"

```
/home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1222:in `initialize': FATAL:  Peer authentication failed for user "alaveteli" (PG::Error)
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1222:in `connect'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:1222:in `connect'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:324:in `initialize'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:28:in `new'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/postgresql_adapter.rb:28:in `postgresql_connection'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `send'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `checkout'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `checkout'
        from /usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `connection'
        from /usr/lib/ruby/1.8/monitor.rb:242:in `synchronize'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/model_schema.rb:310:in `clear_cache!'
        from /home/alaveteli/bundle/ruby/1.8/gems/activerecord-3.2.21/lib/active_record/railtie.rb:103:in `_callback_before_3'
        from /home/alaveteli/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:418:in `_run__644171617__prepare__4__callbacks'
        from /home/alaveteli/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `send'
        from /home/alaveteli/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:405:in `__run_callback'
        from /home/alaveteli/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:385:in `_run_prepare_callbacks'
        from /home/alaveteli/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `send'
        from /home/alaveteli/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/callbacks.rb:81:in `run_callbacks'
        from /home/alaveteli/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/reloader.rb:74:in `prepare!'
        from /home/alaveteli/bundle/ruby/1.8/gems/actionpack-3.2.21/lib/action_dispatch/middleware/reloader.rb:48:in `prepare!'
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/application/finisher.rb:47
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `instance_exec'
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/initializable.rb:30:in `run'
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/initializable.rb:55:in `run_initializers'
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `each'
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/initializable.rb:54:in `run_initializers'
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/application.rb:136:in `initialize!'
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `send'
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /var/www/imamopravoznati/alaveteli/config/environment.rb:5
        from /home/alaveteli/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
        from /home/alaveteli/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
        from /home/alaveteli/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /home/alaveteli/bundle/ruby/1.8/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/application.rb:103:in `require_environment!'
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/commands/runner.rb:44
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/commands.rb:64:in `require'
        from /home/alaveteli/bundle/ruby/1.8/gems/railties-3.2.21/lib/rails/commands.rb:64
        from script/rails:6:in `require'
        from script/rails:6
stalled?
```

**Comment by schlos** [comment]
Might be linked with user permission issue: Install script does not create daemons with correct permissions #2185 seen at https://github.com/mysociety/alaveteli/issues/2185

**Comment by schlos** [comment]
Last time reproducibe on
date:	Mon, Feb 23, 2015 at 7:31 AM

@drutalj solved by changing user permissions/database

under monitoring after upgrade we did yesterday to Alaveteli v0.23

**Comment by schlos** [comment]
Solved with:
https://github.com/codeforcroatia/alaveteli/issues/6#issuecomment-175065591

Not reproducible anymore
