### ISSUE TITLE
Error while posting a comment by admin user

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/alaveteli#88]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Expected Behavior

Session handler should be able to detect that user is logged in and proceed with comment posting. Or ask user to login before posting a comment.

## Current Behavior

My comment was not posted.

## Steps to Reproduce (for bugs)

1. Go make a comment without logging in
2. Before posting a comment, open new tab and login as admin
3. Post comment - comment is not posted (nor I see comment posting confirmation screen)
4. Error email is received

## Context

* Alaveteli version: **0.33.0.0**
* Ruby version: 

**[ERROR] [imamopravoznati.org] comment#new (ActionView::Template::Error) "undefined method `[]' for nil:NilClass"**

```
An ActionView::Template::Error occurred in comment#new:



  undefined method `[]' for nil:NilClass

  app/views/general/_locale_switcher.html.erb:2:in `_app_views_general__locale_switcher_html_erb___3772729498722469798_46961587941680'





-------------------------------

Request:

-------------------------------



  * URL        : http://imamopravoznati.org/annotate/request/datum_izdavanja_dozvola_za_vjetr

  * HTTP Method: POST

  * IP address : xxx.xxx.xxx.xxx

  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "comment"=>{"body"=>"Nažalost, ne vidimo odgovor tijela javne vlasti u kojem je odgovor dostavljen.\r\n\r\n== Možda je odgovor stigao na neku drugu email adresu? ==\r\n\r\nTada savjetujemo podnositeljici zahtjeva da u komentaru ukratko opiše odgovor, a ukoliko je odgovor stigao elektronskim putem i želi odgovor učiniti dostupnim svima koji čitaju ovaj zahtjev da dobiveni odgovor/dokument uploda na neki od javnih servisa za dijeljenje datoteka (npr. na Google Drive, te u komentaru podijelite link kojemu svi mogu pristupiti).\r\n\r\n== Možda je tijelo javne vlasti moglo dostaviti odgovor samo poštanskim putem? ==\r\n\r\nTada slično kao i ranije, predlažemo podnositeljici zahtjeva da poprati zadnji status i opis dobivenog odgovora u komentaru, te statusom označi \"Odgovorit će poštanskim putem\".\r\n\r\nFinalni status (Uspješan odgovor / Nezadovoljavajući odgovor) moguće je postaviti tek kada se na ovoj stranici predmeta prava na pristup informacijama javno vidi odgovor tijela javne vlasti."}, "submitted_comment"=>"1", "preview"=>"1", "commit"=>"Pregledajte Vašu bilješku", "type"=>"request", "controller"=>"comment", "action"=>"new", "url_title"=>"datum_izdavanja_dozvola_za_vjetr"}

  * Timestamp  : 2020-11-12 09:54:53 +0100

  * Server : imamopravoznati.org

  * Rails root : /data/www/imamopravoznati.org/alaveteli

  * Process: 74253


-------------------------------

Backtrace:

-------------------------------



  app/views/general/_locale_switcher.html.erb:2:in `_app_views_general__l=

ocale_switcher_html_erb___3772729498722469798_46961587941680'

  app/views/general/_responsive_header.html.erb:16:in `_app_views_general=

__responsive_header_html_erb___3335157401675106685_46961571302220'

  app/views/layouts/default.html.erb:60:in `_app_views_layouts_default_ht=

ml_erb___2521133987909839000_46961570426500'

  app/controllers/application_controller.rb:192:in `block (2 levels) in r=

ender_exception'

  app/controllers/application_controller.rb:191:in `render_exception'

  lib/strip_empty_sessions.rb:13:in `call'
```

## Your Environment

* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by schlos** [comment]
**[ERROR] [imamopravoznati.org] comment#new (ActionController::InvalidAuthenticityToken) "ActionController::InvalidAuthent...**

```
An ActionController::InvalidAuthenticityToken occurred in comment#new:


  ActionController::InvalidAuthenticityToken
  lib/strip_empty_sessions.rb:13:in `call'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/annotate/request/datum_izdavanja_dozvola_za_vjetr
  * HTTP Method: POST
  * IP address : xxx.xxx.xxx.xxx
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "comment"=>{"body"=>"Nažalost, ne vidimo odgovor tijela javne vlasti u kojem je odgovor dostavljen.\r\n\r\n== Možda je odgovor stigao na neku drugu email adresu? ==\r\n\r\nTada savjetujemo podnositeljici zahtjeva da u komentaru ukratko opiše odgovor, a ukoliko je odgovor stigao elektronskim putem i želi odgovor učiniti dostupnim svima koji čitaju ovaj zahtjev da dobiveni odgovor/dokument uploda na neki od javnih servisa za dijeljenje datoteka (npr. na Google Drive, te u komentaru podijelite link kojemu svi mogu pristupiti).\r\n\r\n== Možda je tijelo javne vlasti moglo dostaviti odgovor samo poštanskim putem? ==\r\n\r\nTada slično kao i ranije, predlažemo podnositeljici zahtjeva da poprati zadnji status i opis dobivenog odgovora u komentaru, te statusom označi \"Odgovorit će poštanskim putem\".\r\n\r\nFinalni status (Uspješan odgovor / Nezadovoljavajući odgovor) moguće je postaviti tek kada se na ovoj stranici predmeta prava na pristup informacijama javno vidi odgovor tijela javne vlasti."}, "submitted_comment"=>"1", "preview"=>"1", "commit"=>"Pregledajte Vašu bilješku", "type"=>"request", "controller"=>"comment", "action"=>"new", "url_title"=>"datum_izdavanja_dozvola_za_vjetr"}
  * Timestamp  : 2020-11-12 09:54:53 +0100
  * Server : imamopravoznati.org
  * Rails root : /data/www/imamopravoznati.org/alaveteli
  * Process: 74253

-------------------------------

Backtrace:

-------------------------------



  lib/strip_empty_sessions.rb:13:in `call'
```

**Comment by schlos** [comment]
Monitoring in the latest SW:

"alaveteli_git_commit": "7618a519c26758ad1b7ef242386a1a87c860f968",
"alaveteli_version": "0.39.1.3",
"ruby_version": "2.5.1",
