### ISSUE TITLE
[ERROR] [imamopravoznati.org] request#new (ActionView::Template::Error) "undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/alaveteli#89]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Alaveteli version: 0.33.0.0
* Ruby version: 

```
An ActionView::Template::Error occurred in request#new:

  undefined method `[]' for nil:NilClass
  app/views/general/_locale_switcher.html.erb:2:in `_app_views_general__locale_switcher_html_erb___3772729498722469798_46961587941680'


-------------------------------
Request:
-------------------------------

  * URL        : http://imamopravoznati.org/new
  * HTTP Method: POST
  * IP address : xxx.xxx.xxx.xxx
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"", "info_request"=>{"title"=>"Protuzakonito odbacivanje otpada građevinske tvrtke Maloižanin d.o.o. ", "public_body_id"=>"33470"}, "outgoing_message"=>{"body"=>"Za: Zavod za prostorno uređenje Zadarske županije, Zadar\r\n\r\nTemeljem Zakona o pravu na pristup informacija molim vas da u elektroničkom obliku, u odgovoru na ovaj email, dostavite sljedeće informacije: \r\n\r\nPišemo Vam u vezi otpada građevinske tvrtke Maloižanin d.o.o. koji je odbačen u otočkom masliniku na zemljišnoj čestici  č.z. 669/230 k.o. Mali Iž. \r\nVlasniku spomenute tvrtke i vlasniku dijela nekretnine na kojoj se nalazi otpad gosp. Ratku Rokovu, je komunalni redar gosp. Dragan Kurtin, nakon utvrđenja kršenja zakona (poslije sedamnaest mjeseci pisanja i ponovljenog očevida) konačno naredio uklanjanje otpada, da bi nas nakon par tjedana isti redar obavijestio o poništenju rješenja i vračanja predmeta na ponovno rješavanje zbog kratkog roka izvršenja i količine otpada.  \r\n \r\nMolimo za objašnjenje po kojem je kriteriju uvažena žalba gosp. Ratka Rokova, kako je utvrđeno da je količina otpada prevelika za rok izvršenja uklanjanja od 20 dana?\r\nKritična količina otpada potvrđuje činjenicu da se radi o građevinskom otpadu tvrtke Maloižanin d.o.o. koji je u toj količini mogao biti odbačen samo koristeći tešku mehanizaciju.\r\nNa kojoj osnovi je procijenjeno da ista mehanizacija nije dostatna za uklanjanje otpada u propisanom roku?\r\n\r\nMolimo za objašnjenje kako je moguće da državna institucija koja je zadužena za zaštitu okoliša, sramotno odugovlači već 17 (sedamnaest) mjeseci sa rješenjem uklanjanja ilegalnog otpada. Zašto se već sedamnaest mjeseci pogoduje privatnom interesu tj. tvrtki Maloižanin d.o.o. na štetu okoliša, podzemnih voda i zdravlja mještana?\r\n\r\nKada će protuzakoniti građevinski otpad biti uklonjen sa č.z. 669/230 k.o. Mali Iž?\r\n\r\n\r\n\r\nS poštovanjem,\r\nMještani otoka Iža"}, "submitted_new_request"=>"1", "preview"=>"1", "commit"=>"Pregledajte Vaš javni zahtjev", "controller"=>"request", "action"=>"new"}
  * Timestamp  : 2020-11-02 09:44:52 +0100
  * Server : imamopravoznati.org
  * Rails root : /data/www/imamopravoznati.org/alaveteli
  * Process: 74253

-------------------------------

Backtrace:

-------------------------------



  app/views/general/_locale_switcher.html.erb:2:in `_app_views_general__l=

ocale_switcher_html_erb___3772729498722469798_46961587941680'

  app/views/general/_responsive_header.html.erb:16:in `_app_views_general=

__responsive_header_html_erb___3335157401675106685_46961571302220'

  app/views/layouts/default.html.erb:60:in `_app_views_layouts_default_ht=

ml_erb___2521133987909839000_46961570426500'

  app/controllers/application_controller.rb:192:in `block (2 levels) in r=

ender_exception'

  app/controllers/application_controller.rb:191:in `render_exception'

  lib/strip_empty_sessions.rb:13:in `call'
```

## Your Environment

* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by schlos** [comment]
Last occurence:
Feb 22, 2021 at 11:08 AM (6 months ago)

**Comment by schlos** [comment]
Not reproducible in 0.39.x.x
