### ISSUE TITLE
[ERROR] [imamopravoznati.org] request#show (ArgumentError) "input string invalid"

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/alaveteli#90]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

* Alaveteli version: 0.33.0.0
* Ruby version: 

```
An ArgumentError occurred in request#show:



  input string invalid

  lib/mail_handler/backends/mail_backend.rb:51:in `block in mail_from_tnef'





-------------------------------

Request:

-------------------------------



  * URL        : http://imamopravoznati.org/request/vijece_roditelja_u_skolskoj_godi_477

  * HTTP Method: GET

  * IP address : xxx.xxx.xxx.xxx

  * Parameters : {"controller"=>"request", "action"=>"show", "url_title"=>"vijece_roditelja_u_skolskoj_godi_477"}

  * Timestamp  : 2020-10-28 11:35:15 +0100

  * Server : imamopravoznati.org

  * Rails root : /data/www/imamopravoznati.org/alaveteli

  * Process: 27441


-------------------------------

Backtrace:

-------------------------------



  lib/mail_handler/backends/mail_backend.rb:51:in `block in mail_from_tne=

f'

  lib/mail_handler/backends/mail_backend.rb:50:in `each'

  lib/mail_handler/backends/mail_backend.rb:50:in `mail_from_tnef'

  lib/mail_handler/backends/mail_backend.rb:196:in `decode_attached_part'=



  lib/mail_handler/backends/mail_backend.rb:241:in `expand_and_normalize_=

parts'

  lib/mail_handler/backends/mail_backend.rb:216:in `block in expand_and_n=

ormalize_parts'

  lib/mail_handler/backends/mail_backend.rb:216:in `expand_and_normalize_=

parts'

  lib/mail_handler/backends/mail_backend.rb:284:in `get_attachment_leaves=

'

  lib/mail_handler/backends/mail_backend.rb:355:in `get_attachment_attrib=

utes'

  app/models/incoming_message.rb:536:in `extract_attachments!'

  app/models/incoming_message.rb:98:in `block in parse_raw_email!'

  app/models/incoming_message.rb:97:in `parse_raw_email!'

  app/models/incoming_message.rb:178:in `mail_from'

  app/models/incoming_message.rb:197:in `safe_mail_from'

  app/models/incoming_message.rb:220:in `specific_from_name?'

  app/views/request/_incoming_correspondence.html.erb:4:in `_app_views_re=

quest__incoming_correspondence_html_erb__1212568653112461048_471053664301=

60'

  app/views/request/_correspondence.html.erb:4:in `_app_views_request__co=

rrespondence_html_erb__1155755488980687871_47105376322980'

  lib/themes/imamopravoznati-theme/lib/views/request/show.html.erb:70:in =

`block in _lib_themes_imamopravoznati_theme_lib_views_request_show_html_e=

rb__1204171911529756522_47105627483200'

  lib/themes/imamopravoznati-theme/lib/views/request/show.html.erb:68:in =

`_lib_themes_imamopravoznati_theme_lib_views_request_show_html_erb__12041=

71911529756522_47105627483200'

  app/controllers/request_controller.rb:133:in `block (3 levels) in show'=



  app/controllers/request_controller.rb:132:in `block in show'

  lib/alaveteli_localization.rb:43:in `with_locale'

  app/controllers/request_controller.rb:83:in `show'

  app/controllers/application_controller.rb:120:in `record_memory'

  lib/strip_empty_sessions.rb:13:in `call'
```

## Your Environment

* Browser Name and version:
* Operating System and version (desktop or mobile):

**Comment by schlos** [comment]
Not reproducible with 0.39.x.x
To be monitored.
